# Generated by Django 5.2.8 on 2025-11-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
