# Generated by Django 5.2.8 on 2025-11-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_mpesa_merchant_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notify_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
